version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: loans_nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./docs:/var/www/html/docs
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - loans_network

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: loans_php
    volumes:
      - ./app:/var/www/html
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=loans
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - loans_network

  postgres:
    image: postgres:15-alpine
    container_name: loans_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=loans
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - loans_network

volumes:
  postgres_data:

networks:
  loans_network:
    driver: bridge