stages:
  - build
  - deploy_resources
  - deploy_services
build_image:
  stage: build
  image: 
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - if [ -z "$CI_COMMIT_TAG" ]; then export IMAGE_TAG="${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"; else export IMAGE_TAG="${CI_COMMIT_TAG}"; fi
    - echo "IMAGE_TAG=$IMAGE_TAG" > image_tag.txt
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile.dev"
      --destination "${CI_REGISTRY_IMAGE}:$IMAGE_TAG"
  artifacts:
    paths:
      - image_tag.txt
  tags:
    - nlu
  only:
    - dev
deploy_resources:
  stage: deploy_resources
  image: bitnami/kubectl
  script:
    - kubectl apply -f k8s/resources/
  tags:
    - nlu
  only:
    - dev

deploy_applications:
  stage: deploy_services
  image: bitnami/kubectl
  script:
    - source image_tag.txt
    - |
      sed -i "s|image: git.abflow.uz:5005/nlu/ms-lottery:latest|image: ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}|" k8s/deployment.yaml
    - kubectl apply -f k8s/deployment.yaml
    - |
  after_script:
    - kubectl rollout status deployment/ms-lottery -n ms
  tags:
    - nlu
  only:
    - dev
