apiVersion: v1
kind: Service
metadata:
  name: ms-payment-service
  namespace: ms
status:
  loadBalancer: {}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
  selector:
    app: ms-payment
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
